# Generated by Django 5.1.2 on 2024-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0003_feedingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='food_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
